import "./globals.css";
import { Icons, ToastContainer } from "react-toastify";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// app/layout.js
export const metadata = {
  title: 'KCL - Kabaddi Champions League Haryana',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/images/footer/main_logo.png', type: 'image/png' }, 
    ],
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ToastContainer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
